server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/fixme_auth?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: fixme_user
    password: Fixme_2025!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
